name: 🔒 Aurora Security Scan

on:
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🏗️ Checkout Aurora Code
      uses: actions/checkout@v4

    - name: 🔍 Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: 🔍 Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: 🐍 Python Security Check
      run: |
        if [ -f "requirements.txt" ]; then
          pip install safety
          safety check -r requirements.txt
        fi

    - name: 🟢 Node.js Security Check
      run: |
        if [ -f "package.json" ]; then
          npm audit --audit-level moderate
        fi

    - name: 🔐 Docker Security Scan
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(pwd):/workspace \
          aquasec/trivy image aurora-test || echo "Docker scan completed"



