global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: 'aurora-town'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'aurora-gpu-worker'
    static_configs:
      - targets: ['209.170.80.132:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['localhost:9187']
