#!/bin/bash
echo "🚀 STARTING AURORA AI TIGHT INTEGRATION"
echo "======================================"
echo ""
echo "🔧 Starting local Robbie Ollama backend..."
python3 /home/allan/aurora-ai-robbiverse/robbie-ollama-backend.py &
echo "✅ Local Robbie Ollama backend started"
echo ""
echo "🔧 Starting RunPod SSH tunnel..."
ssh -i ~/.ssh/id_ed25519 -p 13323 -L 8080:localhost:80 root@209.170.80.132 "echo 'SSH tunnel established on port 8080' && sleep 10" &
echo "✅ RunPod SSH tunnel started"
echo ""
echo "🔧 Starting unified LLM gateway..."
python3 /home/allan/aurora-ai-robbiverse/scripts/unified-llm-gateway.py &
echo "✅ Unified LLM gateway started"
echo ""
echo "🎉 AURORA AI TIGHT INTEGRATION ACTIVE!"
echo "• Local: Robbie Ollama backend (CPU)"
echo "• Remote: RunPod Ollama (RTX 4090 GPU)"
echo "• Gateway: Unified LLM routing"
echo "• Business: HubSpot, Calendar, Contacts"
echo "• Revenue: Deal pipeline, contact scoring"
echo "• Performance: MAX acceleration!"
echo ""
echo "💰 REVENUE IMPACT:"
echo "• Faster code generation"
echo "• Better AI assistance"
echo "• Increased productivity"
echo "• Competitive advantage"
echo "• Ship faster, make more money!"
