version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: robbieverse-postgres
    environment:
      POSTGRES_DB: robbieverse
      POSTGRES_USER: robbie
      POSTGRES_PASSWORD: robbie_dev_2025
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/unified-schema:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U robbie -d robbieverse" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

